import { currentSalesperson } from "@/constants/deal-mock-data";
import type { DealCreationFormValues } from "@/lib/validations/deal";

export const dealCreationDefaultValues: DealCreationFormValues = {
  firstName: "",
  lastName: "",
  mobile: "",
  email: "",
  address: "",
  postcode: "",
  isExistingCustomer: false,
  vehicleId: "",
  hasPartExchange: false,
  pxRegistration: "",
  pxCurrentMileage: undefined,
  pxServiceHistoryType: undefined,
  pxServicedWhere: undefined,
  pxV5InSellersName: undefined,
  pxKeyCount: undefined,
  pxInsuranceWriteOff: undefined,
  pxAccidentHistory: undefined,
  pxAccidentDescription: "",
  pxValueDrivers: [],
  pxFeaturesNotes: "",
  pxConditionNotes: "",
  pxPhotos: [],
  pxValuation: undefined,
  pxExistingFinance: undefined,
  pxLender: undefined,
  pxAgreementNumber: undefined,
  pxMonthlyPayment: undefined,
  pxSettlementFigure: undefined,
  pxSettlementQuoteDate: undefined,
  salesperson: currentSalesperson.name,
  branch: "manchester",
  dealSource: "walk-in",
  purchaseTimeline: "today",
  notes: "",
};
