import type { RecentDeal } from "@/types/dashboard";

export const dealHistoryRecords: RecentDeal[] = [
  {
    id: "DB-1048",
    customer: "Sarah Johnson",
    vehicle: "BMW X3 M Sport 2022",
    financeType: "HP",
    monthlyPayment: 435,
    deposit: "£500 + PX",
    salesperson: "Emma Wilson",
    branch: "manchester",
    status: "won",
    lastUpdated: new Date("2026-06-05"),
  },
  {
    id: "DB-1047",
    customer: "Michael Carter",
    vehicle: "Audi A4 S Line 2021",
    financeType: "PCP",
    monthlyPayment: 299,
    deposit: "£2,000",
    salesperson: "James Brown",
    branch: "leeds",
    status: "presented",
    lastUpdated: new Date("2026-06-05"),
  },
  {
    id: "DB-1046",
    customer: "Olivia Smith",
    vehicle: "VW Golf GTD 2023",
    financeType: "0% Finance",
    monthlyPayment: 512,
    deposit: "£8,200",
    salesperson: "Emma Wilson",
    branch: "manchester",
    status: "draft",
    lastUpdated: new Date("2026-06-05"),
  },
  {
    id: "DB-1045",
    customer: "David Miller",
    vehicle: "Mercedes A180 AMG 2022",
    financeType: "HP",
    monthlyPayment: 378,
    deposit: "£1,000 + PX",
    salesperson: "Tom Harris",
    branch: "birmingham",
    status: "won",
    lastUpdated: new Date("2026-06-04"),
  },
  {
    id: "DB-1044",
    customer: "Chloe White",
    vehicle: "Range Rover Evoque 2021",
    financeType: "PCP",
    monthlyPayment: 449,
    deposit: "£3,500",
    salesperson: "James Brown",
    branch: "leeds",
    status: "lost",
    lastUpdated: new Date("2026-06-04"),
  },
  {
    id: "DB-1043",
    customer: "Liam Taylor",
    vehicle: "Ford Focus ST 2023",
    financeType: "0% Finance",
    monthlyPayment: 465,
    deposit: "£7,900",
    salesperson: "Emma Wilson",
    branch: "manchester",
    status: "finance-pending",
    lastUpdated: new Date("2026-06-04"),
  },
  {
    id: "DB-1042",
    customer: "Sophia Davis",
    vehicle: "BMW 118i Sport 2022",
    financeType: "HP",
    monthlyPayment: 321,
    deposit: "£500",
    salesperson: "Tom Harris",
    branch: "birmingham",
    status: "presented",
    lastUpdated: new Date("2026-06-03"),
  },
  {
    id: "DB-1041",
    customer: "Ethan Wilson",
    vehicle: "Audi Q3 Black Edition 2023",
    financeType: "PCP",
    monthlyPayment: 389,
    deposit: "£2,500",
    salesperson: "James Brown",
    branch: "leeds",
    status: "draft",
    lastUpdated: new Date("2026-06-03"),
  },
  {
    id: "DB-1040",
    customer: "Amelia Moore",
    vehicle: "MINI Cooper S 2022",
    financeType: "0% Finance",
    monthlyPayment: 398,
    deposit: "£6,500",
    salesperson: "Emma Wilson",
    branch: "manchester",
    status: "won",
    lastUpdated: new Date("2026-06-03"),
  },
  {
    id: "DB-1039",
    customer: "Noah Anderson",
    vehicle: "Tesla Model 3 2021",
    financeType: "PCP",
    monthlyPayment: 525,
    deposit: "£4,000",
    salesperson: "Tom Harris",
    branch: "birmingham",
    status: "finance-pending",
    lastUpdated: new Date("2026-06-02"),
  },
];
